### ISSUE TITLE
Tests extending other test classes have double-counted methods

### ISSUE THREAD

**Issue by yurodivuie** [dev9com/parallel-webtest#3]
WebDriverBase currently detect when close the driver by counting test methods.  At present, if a test method is provided by a super class, the method is double counted, and the driver will not close when the test completes.

**Comment by will-iverson** [comment]
Do you have an (ignored) test case checked in?

**Comment by yurodivuie** [comment]
Test added.  See MethodCountTest.

**Comment by yurodivuie** [comment]
Added a fix to WebDriverBase, and more tests to verify the fix.  Should increase performance slightly, as a side effect.  I'll run a build for it this morning; we ran into this in our current project, and it's holding up some work.
