### ISSUE TITLE
This project has been deprecated.

### ISSUE THREAD

**Issue by bootstraponline** [dev9com/parallel-webtest#8]
Hi,

I used this project [3 years ago](http://sauceio.com/index.php/2012/06/testing-githubs-wiki-in-the-cloud/) and it was pretty awesome. I noticed it's deprecated now. Is there a better way to run tests in parallel on Sauce using junit that's not deprecated?

**Comment by will-iverson** [comment]
Short answer: yup, check out junit-webdriver and multi-config-test:

https://github.com/dev9com/junit-webdriver
https://github.com/dev9com/multi-config-test

Slightly longer answer: parallel-webtest mainly did two things, parallel test execution and provide utilities for writing tests.  Nowadays, if you combine the parallel execution of multi-config-test (which can also be used as a template for regular junit tests and junit-webdriver for Selenium, you get better reporting, more flexible config, etc etc.

Glad you like the libraries!

**Comment by bootstraponline** [comment]
Thanks!
